#!/usr/bin/ansible-playbook
##### QNC DEV
---

- name: Effort to maintain credential of BaaS worker servers
  hosts: dev_baas-workers_grp
  gather_facts: "no"
  vars_files:
    - "group_vars/prod-workers"
  pre_tasks:
    - assert:
        that:
          - "usernames is defined"
  tasks:

    - name: read the baas_users file
      shell: "cat /root/baas/baas_users"
      register: ulist
      delegate_to: 127.0.0.1

    - name: Input usernames to baas files
      local_action: lineinfile line="{{ item }}" dest="/root/baas/baas_users" backup=yes
      with_items: "{{ usernames.strip().replace(' ', '').replace(',', '\n').split('\n') }}"
      when: usernames not in ulist.stdout

    # - local_action: lineinfile line="{{ item }}" dest="/root/baas/baas_users" backup=yes
    #   with_items: "{{ usernames.strip().replace(' ', '').replace(',', '\n').split('\n') }}"

    - copy:
        src: /etc/ansible/remote_files/passwd/master.passwd.open_access_ubuntu16
        dest: /root/baas/master.passwd.open_access_ubuntu16
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /etc/ansible/remote_files/automount/auto_homes_qnc
        dest: /var/lib/awx/projects/_56__users_access_to_baas_env_workers_shell_servers/roles/common_infra/files/autofs/auto_homes_qnc
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /etc/ansible/remote_files/automount/auto_homes_qnc
        dest: /var/lib/awx/projects/_56__users_access_to_baas_env_workers_shell_servers/roles/common_infra/files/autofs/auto.homes
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /etc/ansible/remote_files/automount/auto_vols_qnc
        dest: /var/lib/awx/projects/_56__users_access_to_baas_env_workers_shell_servers/roles/common_infra/files/autofs/auto_vols_qnc
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /etc/ansible/remote_files/automount/auto_vols_qnc
        dest: /var/lib/awx/projects/_56__users_access_to_baas_env_workers_shell_servers/roles/common_infra/files/autofs/auto.vols
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /usr/lib/python2.7/site-packages/ansible/modules/custom_modules/gen_pass.py
        dest: /root/baas/gen_pass.py
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - name: Creating prod_users password file
      command: /usr/bin/python /root/baas/gen_pass.py
      delegate_to: 127.0.0.1
      tags: access

    - name: check prod user file exists and not empty
      stat:
        path: /root/baas/prod_users
      register: file_details
      delegate_to: 127.0.0.1
      tags: access

    - shell: "cat /root/baas/prod_users | wc -l"
      delegate_to: 127.0.0.1
      register: line_count

    - name: including roles
      include_role:
        name: workers
      when: file_details.stat.size != 0 and line_count | int > 155

    - name: including roles
      include_role:
        name: common_infra
