- name: Push new /etc/master.passwd file
  template:
    src: templates/worker_base_passwd.j2
    dest: /etc/master.passwd
    backup: yes
  register: new_master_passwd
  tags: access

- name: Copy over /etc/passwd
  copy:
    src: /etc/master.passwd
    dest: /etc/passwd
    remote_src: yes
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: new_master_passwd is changed
  tags: access

- name: Copy over /etc/group file
  template:
    src: templates/worker_base_group.j2
    dest: /etc/group
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: access

- name: Run pwconv
  command: pwconv
  when: new_master_passwd is changed
  tags: access

- name: Create /etc/sudoers.d/BAAS
  template:
    src: templates/managed_sudoers.j2
    dest: /etc/sudoers.d/BAAS
    mode: 0440
    owner: root
    group: root
    validate: '/usr/sbin/visudo -cf %s'
  tags: access

- name: Update /etc/sudoers
  blockinfile:
    state: absent
    path: /etc/sudoers
    block: |
      noormohamed    ALL=(ALL:ALL) ALL
      _devops       ALL=(ALL:ALL) ALL
    validate: '/usr/sbin/visudo -cf %s'
  tags: access

- file:
    path: /tmp/user-construct
    state: directory
  delegate_to: 127.0.0.1

- name: creating new /etc/master.passwd file
  template:
    src: templates/worker_base_passwd.j2
    dest: /tmp/user-construct/master.passwd
  delegate_to: 127.0.0.1

- name: Copy passwd
  copy:
    src: /tmp/user-construct/master.passwd
    dest: /tmp/user-construct/passwd
  delegate_to: 127.0.0.1

- name: Copy over /etc/group file
  template:
    src: templates/worker_base_group.j2
    dest: /tmp/user-construct/group
  delegate_to: 127.0.0.1
